### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE - Ingestion endpoint could not be reached. This batch of telemetry items has been lost. Use Disk Retry Caching to enable resending of failed telemetry. Error:

### ISSUE THREAD

**Issue by LewisPringle** [OfficeDev/office-toolbox#23]
Starting around March 18, 2019 we get:

```
C:\Sandbox\EY\FPP-OfficeAddins2\FPP-Excel-AddIn>npm run sideload

> fpp-excel-addin@0.1.0 sideload C:\Sandbox\EY\FPP-OfficeAddins2\FPP-Excel-AddIn
> office-toolbox sideload -m manifest.xml -a Excel

ApplicationInsights:CorrelationIdManager [ { Error: unable to verify the first certificate
      at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
      at TLSSocket.emit (events.js:189:13)
      at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' } ]
ApplicationInsights:Sender [ 'Ingestion endpoint could not be reached. This batch of telemetry items has been lost. Use Disk Retry Caching to enable resending of failed telemetry. Error:',
  { Error: unable to verify the first certificate
      at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
      at TLSSocket.emit (events.js:189:13)
      at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' } ]
Deleted file: C:\Users\lewis\AppData\Local\Temp\excel add-in 841a65bf-dc23-4a21-8b2b-027515cc18e3.xlsx
Generating file C:\Users\lewis\AppData\Local\Temp\excel add-in 841a65bf-dc23-4a21-8b2b-027515cc18e3.xlsx
Opening file C:\Users\lewis\AppData\Local\Temp\excel add-in 841a65bf-dc23-4a21-8b2b-027515cc18e3.xlsx
For more information about how to sideload Office Add-ins, visit the following link: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins

The run-sideload function still owrks, but this message says there was an erorr
```

**Comment by LewisPringle** [comment]
note - as of around April 1, this problem just disappeared, so presumably someone fixed it?

**Comment by akrantz** [comment]
This seems to no longer be an issue.
